### ISSUE TITLE
ReManga dmca

### ISSUE THREAD

**Issue by e-shl** [keiyoushi/tachiyomi-extensions-source#1651]
### Describe why this should be added

> ReManga (Russian) will not be added back as it has been removed [due to legal reasons](https://github.com/github/dmca). https://github.com/keiyoushi/extensions-source/pull/1526/files

dmca https://github.com/github/dmca/blob/master/2024/02/2024-02-28-recomics.md
it was for a specific licensed manga and not the entire source. Is it possible to restore the source with the introduction of a complete concealment of licensed content
or by rolling back the changes to https://github.com/keiyoushi/extensions-source/pull/959

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
As you can read yourself, it asked for the removal of those specific sources or the entire repo would get locked

**Comment by e-shl** [comment]
> As you can read yourself, it asked for the removal of those specific sources or the entire repo would get locked

and I also see a specific list of links for which there are claims

>     Apotheosis - Elevation to the Status of a God / https://remanga.org/manga/one_hundred_to_make_god
>     How the Demon Emperor became a Butler / https://remanga.org/manga/how-the-demon-emperor-became-a-butler
>     I got into a horror world with a wealth system / https://remanga.org/manga/opening-trillions-of-plutonium
>     I've been stuck on this day for thee thousand years / https://remanga.org/manga/ive-been-stuck-on-this-day-for-thee-thousand-years
>     Evolution frоm the Big Tree / https://remanga.org/manga/evolution-frm-the-big-tree
>     I kill monsters to become stronger / https://remanga.org/manga/gao-wu-landing-10000-years-into-the-future
>     I've been stuck on the same day for a thousand years / https://remanga.org/manga/ive-been-stuck-on-the-same-day-for-a-thousand-years
>     The Iron-Blooded Necromancer Has Returned / https://remanga.org/manga/ironblooded-necromancer-has-returned
>     The Everyone Regressed Except Me / https://remanga.org/manga/the-everyone-regressed-except-me
>     SSS-Rank Lone Summoner / https://remanga.org/manga/only-i-can-use-the-summoning-spell
>     Global Killing: Awakening SSS-level talent! / https://remanga.org/manga/global-killing-awakening-sslevel-talent-at-the-beginning
>     Moon Slayer / https://remanga.org/manga/the-zan-yue
>

**Comment by AwkwardPeak7** [comment]
@e-shl We would like to stay clear of any DMCA threats, so we won't be adding it back (at least anytime in the near future). You may create your own repo to distribute that source.

**Comment by e-shl** [comment]
@e-shl there are guides on how to create it?

**Comment by e-shl** [comment]
@AwkwardPeak7 there are guides on how to create it?

**Comment by AwkwardPeak7** [comment]
There isn't any written guide but basically:

- create project sturucture
  - use  https://github.com/tachiyomiorg/extensions as template since ours is a bit more complicated with dual repo
- add signing key to github secrets
  - `base64 key.jks > output.txt`

**Comment by e-shl** [comment]
> There isn't any written guide but basically:
> 
>     * create project sturucture
>       
>       * use  https://github.com/tachiyomiorg/extensions as template since ours is a bit more complicated with dual repo
> 
>     * add signing key to github secrets
>       
>       * `base64 key.jks > output.txt`

I mean to create a repository that can be used in app
