### ISSUE TITLE
Add anime extension for aniyomi

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [keiyoushi/tachiyomi-extensions-source#2231]
### Describe why this should be added

Can you add some extension for aniyomi because the official extensions have (video list is empty) error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Keiyoushi doesn't have or handle any anime extensions, go check with Aniyomi support instead
