### ISSUE TITLE
Change dependencies `extensions-lib` to a new repo for maintain

### ISSUE THREAD

**Issue by ZIDOUZI** [keiyoushi/tachiyomi-extensions-source#4556]
### Describe your suggested feature

The old repo `tachiyomiorg/extensions-lib` is archived, which lead to new features and possible bugs can't be maintained. Create a new fork and maintain it will be hard but also helpful for mihon ecosystem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
We can't really add new features to the ext-lib without the app also adding it. The Mihon maintainer says they want to make a new source api with new features in the app, sometime in the future so we'll see.

**Comment by ZIDOUZI** [comment]
ext-lib as an api is actually upstream (at least some parts), providing functionality for downstream apps. In my opinion, I've looked at some other apps and have come up with some ideas, such as recommendations for comics, which would require modifying ext-lib first. I think the best way to do this is to create a new ext-lib library for add new api without breaking the current api's, so that downstream apps can make changes based on them.

**Comment by ZIDOUZI** [comment]
of course it would be better if it is maintained by mihon

**Comment by AwkwardPeak7** [comment]
Again, adding anything to ext lib means having to add that functionality in the app too. It is not possible to only have things in the ext lib and not in the app.

The ext lib is a stub library providing compile time dependency for methods and classes in the app. So without corresponding class/method in the app, it won't work.

**Comment by ZIDOUZI** [comment]
Oh oh, sorry, I mistook ext-lib for an api. I guess I got confused with the way other projects do it.

**Comment by AwkwardPeak7** [comment]
closing as not planning for now
